name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "*.pdf"
        artifactContentType: "application/pdf"
        draft: true
        generateReleaseNotes: true
        omitDraftDuringUpdate: true
        skipIfReleaseExists: true
        updateOnlyUnreleased: true
